listener: 
    # host and port of the mongodb used to store scheduled jobs
    mongo_host: 127.0.0.1
    mongo_port: 27017

    # name of the mongodb database to store eventbus related data
    mongo_db: eventbus

    # collection that stores the jobs to be triggered by events 
    mongo_job_collection: jobs

    # interval in seconds in which to poll the mongodb for job definitions 
    mongo_poll_interval: 20

    amq_host: 
    amq_port: 