# Configure where logging will go. 
logger_output: STDOUT

# Log level. Levels are DEBUG, INFO, WARN, ERROR, FATAL.
logger_level: INFO

# ActiveMQ host that runs the STOMP protocol to use as the message broker.  
messaging_host: 127.0.0.1

# Port of the ActiveMQ server  
messaging_port: 61613

# Host of the MongoDB instance where jobs are retrieved from. 
mongo_host: 127.0.0.1

# Port of the MongoDB instance defined above. 
mongo_port: 27017

# Name of the Mongodb database to store jobs information. 
mongo_db: eventbus

# Collection in the above MongoDB database that stores the jobs to be triggered by oplog events. 
mongo_job_collection: jobs

# Interval in seconds in which to poll the mongodb for job definitions. 
mongo_poll_interval: 20

# Directory with jars containing Hadoop jobs (presently not used in production)
hadoop_jars: "./jars"

# Path to the root of the hadoop installation. (Currently used to verify SARJE setup in production.)
hadoop_home: $SARJE_HOME/mock-hadoop
