# Bulk Extract cleanup configuration file.
# Read by cleanup_bulk_extract.rb script upon cleanup of bulk extract files.

# Bulk extract cleanup logging parameters.
log_file_pathname: /var/log/bulkextract/cleanup_bulk_extract.log
log_file_rotation: daily
log_level: INFO

# Bulk extract cleanup variables.
sli_database_name: sli
bulk_extract_host: localhost
bulk_extract_port: 27017
remove_db_record_retries: 3
remove_db_record_retry_interval_secs: 10
