development:
    api_base: https://devapp1.slidev.org/api/rest
    #api_base: http://localhost:8080/api/rest
    #client_id: Eg6eseKRzN
    #client_secret: FqXBla26esaLGcVfhlcLnePOEmeHuez7JpmnR9pLg6RkThqF
    #redirect_uri: http://localhost:3000/callback
test:
    api_base: https://devapp1.slidev.org/api/rest
deployment:
    api_base: https://devapp1.slidev.org/api/rest
integration:
    api_base: https://testapi1.slidev.org/api/rest
