---
default:
    api: &API-DEFAULT

        # Used in api performance tracking
        sli.application.buildTag: sli.app.buildTag
local:
    api:
        <<: *API-DEFAULT
        sli.application.buildTag: sli.app.buildTag
