---

SLI-Common-Config: &COMMON
    sli.admin.client.id: Eg6eseKRzN
    sli.dashboard.client.id: SD7efbdSe4
 
Mongo-Instances: &MONGO-CONFIGURATION
    Mongo: &API-MONGO-1
        sli.api.mongodb.host: prod-dal-1.slidev.org
        sli.api.mongodb.port: 27017
        sli.api.mongodb.user: dallier
 
    Mongo: &INGESTION-MONGO-15
        sli.ingestion.staging.mongodb.database:  ingestion_staging
        sli.ingestion.staging.mongodb.host:  prod-dal-15.slidev.org
        sli.ingestion.staging.mongodb.port:  27017
 
    Mongo: &LOCAL_MONGO
        sli.api.mongodb.host: localhost
        sli.api.mongodb.port: 27017
        sli.api.mongodb.dabase: sli
        sli.ingestion.staging.mongodb.database: ingestion_staging
        sli.ingestion.staging.mongodb.host: localhost

SLI-Service-Group: &PRODUCTION-1
    api-common: &API_COMMON_PROD_1
        <<: *COMMON
        sli.api.base: https://prod-api-1.slidev.org/api/rest
 
    # prod-api-1.slidev.org
    api-host: &PROD-API-1
        <<: *API_COMMON_PROD_1
        <<: *API-MONGO-1
        sli.admin.client.secret: FqXBla26esaLGcVfhlcLnePOEmeHuez7JpmnR9pLg6RkThqF
        sli.admin.redirect.uri: https://prod-api-1.slidev.org:3000/callback...
 
    # prod-ingestion-5.slidev.org
    ingestion-host: &PROD-INGESTION-5
        <<: *API_COMMON_PROD_1
        <<: *INGESTION-MONGO-15
        sli.ingestion.queue.workItem.keystore: /opt/tomcat/ssl/tomcat.keystore
        sli.ingestion.queue.workItem.keystorePassword: changeit
 
    # prod-dashboard-1.slidev.org
    dashboard-host: &PROD-DASHBOARD-1
        <<: *PROD-API-1
        sli.dashboard.name: dashboard1
 
SLI-Service-Group: &LOCAL
    api-common: &API_COMMON_LOCAL
        sli.api.base: http://localhost:8080/api/rest|http://localhost:8080/api/rest
 
    api-host: &API_LOCAL
        <<: *API_COMMON_LOCAL
        <<: *LOCAL_MONGO
        sli.admin.redirect.uri: http://localhost:3000/callback...
 
    ingestion-host: &INGESTION_LOCAL
        <<: *API_LOCAL
