# The root keys match the entity being viewed
# Each key below the root key is in the order those keys should be displayed
# The "default" root key is for nested entities which have no entityType

educationOrganization:
    - id
    - organizationCategories
    - stateOrganizationId
    - nameOfInstitution
    - address

staff:
    - loginid
    - stateid
    - id
    - staffUniqueStateId
    - name
    - address
    - electronicMail
    - phoneNumber
    - birthDate
    - degree
    - gender
    - credentials
    - yearsTeachingExperience
    - yearsExperience
    - entityType
    - race
    - hispanic
    - oldEthnicity

default:
    - apartmentRoomSuiteNumber
    - streetNumberName
    - city
    - stateAbbreviation
    - postalCode
    - addressType
    - personalTitlePrefix
    - firstName
    - lastSurname
    - verification
    - emailAddress
