#The root key is for the entity type, it needs to match the url_type that is passed through.
#Each key below is the key to be displayed for the simple view

student:
    - name/lastSurname
    - name/firstName
    - studentUniqueStateId
    - id

parent:
    - name/lastSurname
    - name/firstName
    - parentUniqueStateId
    - id

teacher:
    - name/lastSurname
    - name/firstName
    - staffUniqueStateId
    - id
    
school:
    - id
    - nameOfInstitution
    - stateOrganizationId
    #This is actually an array.
    - address/city
    
section:
    - uniqueSectionCode
    - educationalEnvironment
    - availableCredit

staff:
    - name/lastSurname
    - name/firstName
    - staffUniqueStateId
    - id

# Paginate items per page. The first number will be the default
# This will be all of the options available
paginate_ipp:
    - 25
    - 50
    - 100

# Number of ingestion jobs to show on the home page
ingestion_jobs: 5
