#The root key is for the entity type, it needs to match the url_type that is passed through.
#Each key below is the key to be displayed for the simple view

student:
    - id
    - name/firstName
    - name/lastSurname
teacher:
    - id
    - sex
    - name/firstName
    - name/lastSurname
    
school:
    - id
    - nameOfInstitution
    #This is actually an array.
    # - address/city
